### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by nathanweeks**
A user on our HPC cluster encountered difficulties installing IMCoalHMM, initially due to an issue with the [ziphmm](https://pypi.org/project/ziphmm/) dependency:
```
$ pip install ziphmm
...
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nufYpa/ziphmm/setup.py", line 18, in <module>
        "ziphmm/cython_funcs.pyx",
      File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 908, in cythonize
        aliases=aliases)
      File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 778, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 124, in nonempty
        raise ValueError(error_msg)
    ValueError: 'ziphmm/cython_funcs.pyx' doesn't match any files
```
It appears the ziphmm-0.1.0 package is missing cython_funcs.pyx:
```
$ tar -xzvf ziphmm-0.1.0.tar.gz
ziphmm-0.1.0/
ziphmm-0.1.0/README.rst
ziphmm-0.1.0/ziphmm/
ziphmm-0.1.0/ziphmm/cython_funcs.c
ziphmm-0.1.0/ziphmm/wrappers.py
ziphmm-0.1.0/ziphmm/__init__.py
ziphmm-0.1.0/PKG-INFO
ziphmm-0.1.0/ziphmm.egg-info/
ziphmm-0.1.0/ziphmm.egg-info/top_level.txt
ziphmm-0.1.0/ziphmm.egg-info/dependency_links.txt
ziphmm-0.1.0/ziphmm.egg-info/PKG-INFO
ziphmm-0.1.0/ziphmm.egg-info/SOURCES.txt
ziphmm-0.1.0/setup.py
ziphmm-0.1.0/setup.cfg
```
This PR proposes adding a Dockerfile to enable a reproducible build of IMCoalHMM that can be executed on a local workstation with Docker, and optionally exported to a Singularity image using [docker2singularity](https://github.com/singularityhub/docker2singularity) for execution in a multi-tenant HPC cluster environment.

I haven't thoroughly tested the advertised scripts (prepare-alignments.py, isolation-model.py, initial-migration-model.py; it looks like the others in scripts/ aren't necessarily supported?), but a user is evaluating them using the resulting Singularity image.

### CODE REVIEW

**Comment by mailund** [comment]
I have never done anything with Docker, so I wouldn't know how to test this. I am happy to merge, but @birc-aeh you have some experience with both Docker and IMCoalHMM you might have an opinion?

If I don't hear anything, I am going to blindly merge in a day or two, because it sounds like a great idea to have an image. I just don't know how to test it.

**Comment by birc-aeh** [comment]
Looks good to me - the dockerfile works and ziphmm works inside the resulting docker image.
I also managed to get `isolation-model.py` to run on some output from `prepare-alignments.py`.

I'm not sure how great a state the actual IMCoalHMM code is in though :smile:

**Comment by mailund** [comment]
It isn't in a perfect state. It's been a while since we used it. But if people can find a use for it, I am fine with merging.

**Comment by nathanweeks** [comment]
FWIW, the colleague who is testing the containerized IMCoalHMM encountered an error in prepare-alignments.py due to a missing import statement (fixed in https://github.com/mailund/IMCoalHMM/pull/3/commits/d3b1916711cbbc1946e47c4c8a41b17dd46c084d)

**Comment by mailund** [comment]
Yeah, the code is pretty old by now, and I haven't run it for years, so there are bound to be some issues...

**Pull request merged**
